name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Build
        run: npm run build:ci

      # - name: Test (100% coverage enforced)
      #   run: npm run test:ci
