name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.11.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.x # or 20.8.1 minimum

      - run: node -v # ✅ should print v20.11.0 or similar

      - run: npm ci

      - run: npm run build

      - name: Run semantic-release (npm + GitHub release)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
